<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sign in | Transit Desk</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet"><link href="{{ asset('css/app.css') }}" rel="stylesheet"><link href="{{ asset('css/auth.css') }}" rel="stylesheet"></head>
<body class="login-page" style="--school-image: url('{{ asset('images/school-building.jfif') }}')">
<main class="login-art"><div class="seal"><i class="bi bi-building-fill"></i></div><div class="eyebrow">MUNICIPAL OPERATIONS</div><h1>Transit Desk</h1><div class="brand-subtitle">Municipal Operations</div><p>Municipal Tricycle and Public Transport Permitting, Franchise Management, and Violation Tracking.</p><div class="art-footer">OPERATIONS PORTAL <span>•</span> v1.0</div></main>
<section class="login-panel" aria-label="Sign in"><div class="login-box"><div class="eyebrow">SECURE ACCESS</div><h2>Welcome back.</h2><p class="muted">Sign in to manage municipal transport operations.</p>
@if(session('success'))<div class="alert alert-success py-2">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger py-2">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('login.attempt') }}">@csrf<div class="mb-3"><label class="form-label" for="login">Username or email</label><div class="input-group"><span class="input-group-text"><i class="bi bi-person"></i></span><input id="login" name="login" class="form-control" value="{{ old('login') }}" autocomplete="username" required autofocus></div></div><div class="mb-3"><div class="d-flex justify-content-between"><label class="form-label" for="login-password">Password</label><span class="muted small">Protected account</span></div><div class="input-group"><span class="input-group-text"><i class="bi bi-lock"></i></span><input id="login-password" name="password" type="password" class="form-control" autocomplete="current-password" required><button class="btn password-toggle" type="button" aria-label="Show password" title="Show password" onclick="toggleLoginPassword(this)"><i class="bi bi-eye"></i></button></div></div><div class="form-check mb-4"><input class="form-check-input" type="checkbox" name="remember" id="remember"><label class="form-check-label" for="remember">Keep me signed in</label></div><button class="btn btn-primary w-100 py-2">Sign in to Transit Desk <i class="bi bi-arrow-right ms-2"></i></button></form><p class="login-note">New to Transit Desk? <a href="{{ route('register') }}">Create an account</a></p><p class="login-note"><i class="bi bi-shield-check me-1"></i> Authorized municipal personnel only</p></div></section>
<script>function toggleLoginPassword(button){const input=document.getElementById('login-password');const visible=input.type==='text';input.type=visible?'password':'text';button.querySelector('i').className=visible?'bi bi-eye':'bi bi-eye-slash';button.setAttribute('aria-label',visible?'Show password':'Hide password');button.title=visible?'Show password':'Hide password';}</script>
</body></html>
